global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "strawberry"
    static_configs:
      - targets: ["strawberry:8000"]

remote_write:
  - url: ...
    basic_auth:
      username: ...
      password: ...
