{
 "title": "strawberry",
 "description": "🍓 Strawberry is large language models benchmark inference tool that allows to compare different inference servers and evaluate them under particular load conditions",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "run",
    "label": "run",
    "query": {
     "query": "label_values(response_code_total,run)"
    }
   },
   { "name": "range", "label": "Range", "query": "15s,1m,3m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "timeseries",
   "description": "Number of active users",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "users" } },
   "targets": [
    {
     "expr": "users{run=\"$run\"}",
     "legendFormat": "{{run}}"
    }
   ]
  },
  {
   "title": "Request RPS",
   "type": "timeseries",
   "description": "Requests per second that go to server",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(requests_count_total{run=\"$run\"}[$range]))",
     "legendFormat": "{{run}}"
    }
   ]
  },
  {
   "title": "TPOT By Percentiles",
   "type": "timeseries",
   "description": "Time Per Output Token Latency By Percentiles",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(rate(request_time_per_output_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "99P"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(request_time_per_output_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "95P"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum(rate(request_time_per_output_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "90P"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum(rate(request_time_per_output_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "75P"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum(rate(request_time_per_output_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "50P"
    }
   ]
  },
  {
   "title": "Latency By Percentiles",
   "type": "timeseries",
   "description": "Total Request Latency By Percentiles",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(rate(request_total_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "99P"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(request_total_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "95P"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum(rate(request_total_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "90P"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum(rate(request_total_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "75P"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum(rate(request_total_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "50P"
    }
   ]
  },
  {
   "title": "TTFT By Percentiles",
   "type": "timeseries",
   "description": "Time To First Token Latency By Percentiles",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum(rate(request_time_to_first_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "99P"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(request_time_to_first_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "95P"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum(rate(request_time_to_first_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "90P"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum(rate(request_time_to_first_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "75P"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum(rate(request_time_to_first_token_latency_seconds_bucket{run=\"$run\"}[$range])) by (le)\n)",
     "legendFormat": "50P"
    }
   ]
  },
  {
   "title": "Goodput",
   "type": "timeseries",
   "description": "Requests per second that have total latency lower than. +inf is equal to default RPS metric",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(request_total_latency_seconds_bucket{run=\"$run\", le=\"+Inf\"}[$range]))",
     "legendFormat": "+Inf"
    },
    {
     "expr": "sum(rate(request_total_latency_seconds_bucket{run=\"$run\", le=\"10.0\"}[$range]))",
     "legendFormat": "10s"
    },
    {
     "expr": "sum(rate(request_total_latency_seconds_bucket{run=\"$run\", le=\"5.0\"}[$range]))",
     "legendFormat": "5s"
    },
    {
     "expr": "sum(rate(request_total_latency_seconds_bucket{run=\"$run\", le=\"1.0\"}[$range]))",
     "legendFormat": "1s"
    }
   ]
  },
  {
   "title": "Processed Tokens Count Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "targets": [
    {
     "expr": "(\n  sum by (run)(rate(prefill_tokens_sum{run=\"$run\"}[$range]))\n /\n  sum by (run)(rate(prefill_time_seconds_sum{run=\"$run\"}[$range]))\n)\n* on(run) group_left() (users{run=\"$run\"})",
     "legendFormat": "prefill"
    },
    {
     "expr": "(\n  sum by (run)(rate(decode_tokens_sum{run=\"$run\"}[$range]))\n /\n  sum by (run)(rate(decode_time_seconds_sum{run=\"$run\"}[$range]))\n)\n* on(run) group_left() (users{run=\"$run\"})",
     "legendFormat": "decode"
    }
   ]
  },
  {
   "title": "Prefill Tokens Per Request By Percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(prefill_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "99P"
    },
    {
     "expr": "histogram_quantile(0.95, rate(prefill_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "95P"
    },
    {
     "expr": "histogram_quantile(0.90, rate(prefill_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "90P"
    },
    {
     "expr": "histogram_quantile(0.75, rate(prefill_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "75P"
    },
    {
     "expr": "histogram_quantile(0.50, rate(prefill_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "50P"
    }
   ]
  },
  {
   "title": "Decode Tokens Per Request By Percentile",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "tokens" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(decode_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "99P"
    },
    {
     "expr": "histogram_quantile(0.95, rate(decode_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "95P"
    },
    {
     "expr": "histogram_quantile(0.90, rate(decode_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "90P"
    },
    {
     "expr": "histogram_quantile(0.75, rate(decode_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "75P"
    },
    {
     "expr": "histogram_quantile(0.50, rate(decode_tokens_bucket{run=\"$run\"}[$range]))",
     "legendFormat": "50P"
    }
   ]
  },
  {
   "title": "Status coded total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (code) (response_code_total{run=\"$run\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total prompt tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "prefill_tokens_sum{run=\"$run\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total decode tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "decode_tokens_sum{run=\"$run\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}