name: Build and push release docker image

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
      
      - name: Configure qemu
        uses: docker/setup-qemu-action@v3
      
      - name: Configure buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push release docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/strawberry:${{ github.ref_name }}
